export const architecturalStyles: any[] = [
  { name: "Achaemenid", id: 0 },
  { name: "American craftsman", id: 1 },
  { name: "American Foursquare", id: 2 },
  { name: "Ancient Egyptian", id: 3 },
  { name: "Art Deco", id: 4 },
  { name: "Art Nouveau", id: 5 },
  { name: "Baroque", id: 6 },
  { name: "Bauhaus", id: 7 },
  { name: "Beaux-Arts", id: 8 },
  { name: "Byzantine", id: 9 },
  { name: "Chicago school", id: 10 },
  { name: "Colonial", id: 11 },
  { name: "Deconstructivism", id: 12 },
  { name: "Edwardian", id: 13 },
  { name: "Georgian", id: 14 },
  { name: "Gothic", id: 15 },
  { name: "Greek Revival", id: 16 },
  { name: "International style", id: 17 },
  { name: "Novelty", id: 18 },
  { name: "Palladian", id: 19 },
  { name: "Postmodern", id: 20 },
  { name: "Queen Anne", id: 21 },
  { name: "Romanesque", id: 22 },
  { name: "Russian Revival", id: 23 },
  { name: "Tudor Revival", id: 24 },
];
