export const architecturalStyles: any[] = [
  { name: "Achaemenid", id: 0 },
  { name: "American craftsman", id: 1 },
  { name: "American Foursquare", id: 2 },
  { name: "Ancient Egyptian", id: 3 },
  { name: "Art Deco", id: 4 },
  { name: "Art Nouveau", id: 5 },
  { name: "Baroque", id: 6 },
  { name: "Bauhaus", id: 7 },
  { name: "Beaux-Arts", id: 8 },
  { name: "Byzantine", id: 9 },
  { name: "Chicago school", id: 10 },
  { name: "Colonial", id: 11 },
  { name: "Deconstructivism", id: 12 },
  { name: "Edwardian", id: 13 },
  { name: "Georgian", id: 14 },
  { name: "Gothic", id: 15 },
  { name: "Greek Revival", id: 16 },
  { name: "International style", id: 17 },
  { name: "Novelty", id: 18 },
  { name: "Palladian", id: 19 },
  { name: "Postmodern", id: 20 },
  {
    name: "Queen Anne",
    id: 21,
    image:
      "https://www.thoughtco.com/thmb/UWQq1xhkEKjD0ixd5_dFxTPmVqE=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/architecture-queenanne-Pollock-Capps-House-564106841-5abdaea2c67335003757ef89.jpg",
    about:
      "The Queen Anne style in British architecture refers to either the English Baroque architectural style that developed around the time of Queen Anne (who reigned from 1702 to 1714) or a revived form that became popular during the last quarter of the 19th century and the early decades of the 20th century (which is known as Queen Anne Revival).In other English-speaking parts of the world, Queen Anne style refers to entirely different styles.",
  },
  { name: "Romanesque", id: 22 },
  { name: "Russian Revival", id: 23 },
  { name: "Tudor Revival", id: 24 },
];
